In [1]:
import requests

url = "https://cricsheet.org/downloads/ipl_csv2.zip"

response = requests.get(url)
response.raise_for_status()

with open("ipl_csv2.zip", "wb") as f:
  f.write(response.content)

print("Download complete")

Download complete

In [2]:
import zipfile

with zipfile.ZipFile("ipl_csv2.zip", "r") as zip_ref:
    zip_ref.extractall("ipl_data")

print("Extracted successfully.")

Extracted successfully.

In [3]:
from pathlib import Path

data_path = Path("ipl_data")

files = list(data_path.iterdir())

print("Number of files:", len(files))
print(files[:10])

Number of files: 2489
[PosixPath('ipl_data/1136564.csv'), PosixPath('ipl_data/729297.csv'), PosixPath('ipl_data/829765.csv'), PosixPath('ipl_data/729293_info.csv'), PosixPath('ipl_data/598056_info.csv'), PosixPath('ipl_data/1082650_info.csv'), PosixPath('ipl_data/829727_info.csv'), PosixPath('ipl_data/419158.csv'), PosixPath('ipl_data/1178410_info.csv'), PosixPath('ipl_data/734041.csv')]

In [4]:
info_files = list(data_path.glob("*_info.csv"))

print("Info files:", len(info_files))
print("\nFirst info file:", info_files[0])

with open(info_files[0], "r", encoding="utf-8") as f:
    for i in range(20):
        print(f.readline().rstrip())

Info files: 1243

First info file: ipl_data/729293_info.csv
version,2.3.0
info,balls_per_over,6
info,team,Chennai Super Kings
info,team,Delhi Daredevils
info,team_type,club
info,gender,male
info,season,2014
info,date,2014/04/21
info,event,Indian Premier League
info,match_id,729293
info,match_type,T20
info,overs,20
info,match_number,8
info,venue,Sheikh Zayed Stadium
info,city,Abu Dhabi
info,toss_winner,Chennai Super Kings
info,toss_decision,bat
info,player_of_match,SK Raina
info,umpire,RK Illingworth
info,umpire,C Shamshuddin

In [5]:
import csv

with open(info_files[0], "r", encoding="utf-8") as f:
    rows = list(csv.reader(f))

for row in rows:
    print(row)

['version', '2.3.0']
['info', 'balls_per_over', '6']
['info', 'team', 'Chennai Super Kings']
['info', 'team', 'Delhi Daredevils']
['info', 'team_type', 'club']
['info', 'gender', 'male']
['info', 'season', '2014']
['info', 'date', '2014/04/21']
['info', 'event', 'Indian Premier League']
['info', 'match_id', '729293']
['info', 'match_type', 'T20']
['info', 'overs', '20']
['info', 'match_number', '8']
['info', 'venue', 'Sheikh Zayed Stadium']
['info', 'city', 'Abu Dhabi']
['info', 'toss_winner', 'Chennai Super Kings']
['info', 'toss_decision', 'bat']
['info', 'player_of_match', 'SK Raina']
['info', 'umpire', 'RK Illingworth']
['info', 'umpire', 'C Shamshuddin']
['info', 'reserve_umpire', 'K Srinath']
['info', 'tv_umpire', 'HDPK Dharmasena']
['info', 'match_referee', 'GF Labrooy']
['info', 'target_overs', '2', '20']
['info', 'target_runs', '2', '178']
['info', 'winner', 'Chennai Super Kings']
['info', 'winner_runs', '93']
['info', 'player', 'Chennai Super Kings', 'DR Smith']
['info', 'player', 'Chennai Super Kings', 'BB McCullum']
['info', 'player', 'Chennai Super Kings', 'SK Raina']
['info', 'player', 'Chennai Super Kings', 'F du Plessis']
['info', 'player', 'Chennai Super Kings', 'MS Dhoni']
['info', 'player', 'Chennai Super Kings', 'RA Jadeja']
['info', 'player', 'Chennai Super Kings', 'M Manhas']
['info', 'player', 'Chennai Super Kings', 'R Ashwin']
['info', 'player', 'Chennai Super Kings', 'BW Hilfenhaus']
['info', 'player', 'Chennai Super Kings', 'MM Sharma']
['info', 'player', 'Chennai Super Kings', 'IC Pandey']
['info', 'player', 'Delhi Daredevils', 'MA Agarwal']
['info', 'player', 'Delhi Daredevils', 'M Vijay']
['info', 'player', 'Delhi Daredevils', 'KD Karthik']
['info', 'player', 'Delhi Daredevils', 'MK Tiwary']
['info', 'player', 'Delhi Daredevils', 'JP Duminy']
['info', 'player', 'Delhi Daredevils', 'LRPL Taylor']
['info', 'player', 'Delhi Daredevils', 'JDS Neesham']
['info', 'player', 'Delhi Daredevils', 'S Nadeem']
['info', 'player', 'Delhi Daredevils', 'Mohammed Shami']
['info', 'player', 'Delhi Daredevils', 'JD Unadkat']
['info', 'player', 'Delhi Daredevils', 'NM Coulter-Nile']
['info', 'registry', 'people', 'BB McCullum', 'b8a55852']
['info', 'registry', 'people', 'BW Hilfenhaus', 'f3171936']
['info', 'registry', 'people', 'C Shamshuddin', '0f9d921b']
['info', 'registry', 'people', 'DR Smith', '35205dfc']
['info', 'registry', 'people', 'F du Plessis', '3355b542']
['info', 'registry', 'people', 'GF Labrooy', '8e088dbc']
['info', 'registry', 'people', 'HDPK Dharmasena', '323e4c16']
['info', 'registry', 'people', 'IC Pandey', 'e0407c01']
['info', 'registry', 'people', 'JD Unadkat', '1e66c162']
['info', 'registry', 'people', 'JDS Neesham', '9219eff0']
['info', 'registry', 'people', 'JP Duminy', '2e8994e7']
['info', 'registry', 'people', 'K Srinath', '8ab5da97']
['info', 'registry', 'people', 'KD Karthik', 'c03f1114']
['info', 'registry', 'people', 'LRPL Taylor', 'b61a3e1a']
['info', 'registry', 'people', 'M Manhas', 'c42aaf71']
['info', 'registry', 'people', 'M Vijay', '4b57e452']
['info', 'registry', 'people', 'MA Agarwal', '00ea847a']
['info', 'registry', 'people', 'MK Tiwary', '26e5cabf']
['info', 'registry', 'people', 'MM Sharma', '759ac88f']
['info', 'registry', 'people', 'MS Dhoni', '4a8a2e3b']
['info', 'registry', 'people', 'Mohammed Shami', '8cf9814c']
['info', 'registry', 'people', 'NM Coulter-Nile', '56ab442f']
['info', 'registry', 'people', 'R Ashwin', '495d42a5']
['info', 'registry', 'people', 'RA Jadeja', 'fe93fd9d']
['info', 'registry', 'people', 'RK Illingworth', '20672246']
['info', 'registry', 'people', 'S Nadeem', '9d80c5e1']
['info', 'registry', 'people', 'SK Raina', '1dc12ab9']
['info', 'registry', 'people', 'WD Parnell', '3a60e0b5']

In [6]:
import pandas as pd

rows[:10]

[['version', '2.3.0'],
 ['info', 'balls_per_over', '6'],
 ['info', 'team', 'Chennai Super Kings'],
 ['info', 'team', 'Delhi Daredevils'],
 ['info', 'team_type', 'club'],
 ['info', 'gender', 'male'],
 ['info', 'season', '2014'],
 ['info', 'date', '2014/04/21'],
 ['info', 'event', 'Indian Premier League'],
 ['info', 'match_id', '729293']]

In [7]:
info_data = {}

for row in rows:
    if row[0] == "info":
        key = row[1]
        value = row[2:]

        if key not in info_data:
            info_data[key] = []

        info_data[key].append(value)

info_data

{'balls_per_over': [['6']],
 'team': [['Chennai Super Kings'], ['Delhi Daredevils']],
 'team_type': [['club']],
 'gender': [['male']],
 'season': [['2014']],
 'date': [['2014/04/21']],
 'event': [['Indian Premier League']],
 'match_id': [['729293']],
 'match_type': [['T20']],
 'overs': [['20']],
 'match_number': [['8']],
 'venue': [['Sheikh Zayed Stadium']],
 'city': [['Abu Dhabi']],
 'toss_winner': [['Chennai Super Kings']],
 'toss_decision': [['bat']],
 'player_of_match': [['SK Raina']],
 'umpire': [['RK Illingworth'], ['C Shamshuddin']],
 'reserve_umpire': [['K Srinath']],
 'tv_umpire': [['HDPK Dharmasena']],
 'match_referee': [['GF Labrooy']],
 'target_overs': [['2', '20']],
 'target_runs': [['2', '178']],
 'winner': [['Chennai Super Kings']],
 'winner_runs': [['93']],
 'player': [['Chennai Super Kings', 'DR Smith'],
  ['Chennai Super Kings', 'BB McCullum'],
  ['Chennai Super Kings', 'SK Raina'],
  ['Chennai Super Kings', 'F du Plessis'],
  ['Chennai Super Kings', 'MS Dhoni'],
  ['Chennai Super Kings', 'RA Jadeja'],
  ['Chennai Super Kings', 'M Manhas'],
  ['Chennai Super Kings', 'R Ashwin'],
  ['Chennai Super Kings', 'BW Hilfenhaus'],
  ['Chennai Super Kings', 'MM Sharma'],
  ['Chennai Super Kings', 'IC Pandey'],
  ['Delhi Daredevils', 'MA Agarwal'],
  ['Delhi Daredevils', 'M Vijay'],
  ['Delhi Daredevils', 'KD Karthik'],
  ['Delhi Daredevils', 'MK Tiwary'],
  ['Delhi Daredevils', 'JP Duminy'],
  ['Delhi Daredevils', 'LRPL Taylor'],
  ['Delhi Daredevils', 'JDS Neesham'],
  ['Delhi Daredevils', 'S Nadeem'],
  ['Delhi Daredevils', 'Mohammed Shami'],
  ['Delhi Daredevils', 'JD Unadkat'],
  ['Delhi Daredevils', 'NM Coulter-Nile']],
 'registry': [['people', 'BB McCullum', 'b8a55852'],
  ['people', 'BW Hilfenhaus', 'f3171936'],
  ['people', 'C Shamshuddin', '0f9d921b'],
  ['people', 'DR Smith', '35205dfc'],
  ['people', 'F du Plessis', '3355b542'],
  ['people', 'GF Labrooy', '8e088dbc'],
  ['people', 'HDPK Dharmasena', '323e4c16'],
  ['people', 'IC Pandey', 'e0407c01'],
  ['people', 'JD Unadkat', '1e66c162'],
  ['people', 'JDS Neesham', '9219eff0'],
  ['people', 'JP Duminy', '2e8994e7'],
  ['people', 'K Srinath', '8ab5da97'],
  ['people', 'KD Karthik', 'c03f1114'],
  ['people', 'LRPL Taylor', 'b61a3e1a'],
  ['people', 'M Manhas', 'c42aaf71'],
  ['people', 'M Vijay', '4b57e452'],
  ['people', 'MA Agarwal', '00ea847a'],
  ['people', 'MK Tiwary', '26e5cabf'],
  ['people', 'MM Sharma', '759ac88f'],
  ['people', 'MS Dhoni', '4a8a2e3b'],
  ['people', 'Mohammed Shami', '8cf9814c'],
  ['people', 'NM Coulter-Nile', '56ab442f'],
  ['people', 'R Ashwin', '495d42a5'],
  ['people', 'RA Jadeja', 'fe93fd9d'],
  ['people', 'RK Illingworth', '20672246'],
  ['people', 'S Nadeem', '9d80c5e1'],
  ['people', 'SK Raina', '1dc12ab9'],
  ['people', 'WD Parnell', '3a60e0b5']]}

In [8]:
match_data = {
    "match_id": info_data["match_id"][0][0],
    "season": info_data["season"][0][0],
    "date": info_data["date"][0][0],
    "team_1": info_data["team"][0][0],
    "team_2": info_data["team"][1][0],
    "venue": info_data["venue"][0][0],
    "city": info_data["city"][0][0],
    "toss_winner": info_data["toss_winner"][0][0],
    "toss_decision": info_data["toss_decision"][0][0],
    "player_of_match": info_data["player_of_match"][0][0],
    "winner": info_data["winner"][0][0],
    "winner_runs": info_data["winner_runs"][0][0]
}

match_data

{'match_id': '729293',
 'season': '2014',
 'date': '2014/04/21',
 'team_1': 'Chennai Super Kings',
 'team_2': 'Delhi Daredevils',
 'venue': 'Sheikh Zayed Stadium',
 'city': 'Abu Dhabi',
 'toss_winner': 'Chennai Super Kings',
 'toss_decision': 'bat',
 'player_of_match': 'SK Raina',
 'winner': 'Chennai Super Kings',
 'winner_runs': '93'}

In [10]:
matches = []

for info_file in info_files:
    with open(info_file, "r", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    info_data = {}

    for row in rows:
        if row[0] == "info":
            key = row[1]
            value = row[2:]

            if key not in info_data:
                info_data[key] = []

            info_data[key].append(value)

    match_data = {
        "match_id": info_data["match_id"][0][0],
        "season": info_data["season"][0][0],
        "date": info_data["date"][0][0],
        "team_1": info_data["team"][0][0],
        "team_2": info_data["team"][1][0],
        "venue": info_data["venue"][0][0],
        "city": info_data["city"][0][0],
        "toss_winner": info_data["toss_winner"][0][0],
        "toss_decision": info_data["toss_decision"][0][0],
        "player_of_match": info_data.get("player_of_match", [[None]])[0][0],
        "winner": info_data.get("winner", [[None]])[0][0],
        "winner_runs": info_data.get("winner_runs", [[None]])[0][0]
    }

    matches.append(match_data)

In [11]:
len(matches)

1243

In [12]:
df = pd.DataFrame(matches)

df.head()

,match_id,season,date,team_1,team_2,venue,city,toss_winner,toss_decision,player_of_match,winner,winner_runs
0,729293,2014,2014/04/21,Chennai Super Kings,Delhi Daredevils,Sheikh Zayed Stadium,Abu Dhabi,Chennai Super Kings,bat,SK Raina,Chennai Super Kings,93
1,598056,2013,2013/05/11,Kings XI Punjab,Sunrisers Hyderabad,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Kings XI Punjab,field,PA Patel,Sunrisers Hyderabad,30
2,1082650,2017,2017/05/21,Mumbai Indians,Rising Pune Supergiant,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Mumbai Indians,bat,KH Pandya,Mumbai Indians,1
3,829727,2015,2015/04/16,Sunrisers Hyderabad,Rajasthan Royals,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Visakhapatnam,Rajasthan Royals,field,AM Rahane,Rajasthan Royals,None
4,1178410,2019,2019/04/19,Royal Challengers Bangalore,Kolkata Knight Riders,Eden Gardens,Kolkata,Kolkata Knight Riders,field,V Kohli,Royal Challengers Bangalore,10

In [13]:
df.shape, df.dtypes

((1243, 12),
 match_id           object
 season             object
 date               object
 team_1             object
 team_2             object
 venue              object
 city               object
 toss_winner        object
 toss_decision      object
 player_of_match    object
 winner             object
 winner_runs        object
 dtype: object)

In [15]:
df["date"] = pd.to_datetime(df["date"])
df["winner_runs"] = pd.to_numeric(df["winner_runs"])

df.dtypes

match_id                   object
season                     object
date               datetime64[ns]
team_1                     object
team_2                     object
venue                      object
city                       object
toss_winner                object
toss_decision              object
player_of_match            object
winner                     object
winner_runs               float64
dtype: object