In [6]:
import requests

url = "https://cricsheet.org/downloads/ipl_csv2.zip"

response = requests.get(url)
response.raise_for_status()

with open("ipl_csv2.zip", "wb") as f:
  f.write(response.content)

print("Download complete")

Download complete

In [7]:
import zipfile

with zipfile.ZipFile("ipl_csv2.zip", "r") as zip_ref:
    zip_ref.extractall("ipl_data")

print("Extracted successfully.")

Extracted successfully.

In [8]:
from pathlib import Path

data_path = Path("ipl_data")

files = list(data_path.iterdir())

print("Number of files:", len(files))
print(files[:10])

Number of files: 2488
[PosixPath('ipl_data/1529264_info.csv'), PosixPath('ipl_data/1082603_info.csv'), PosixPath('ipl_data/598019.csv'), PosixPath('ipl_data/1237181.csv'), PosixPath('ipl_data/1304065_info.csv'), PosixPath('ipl_data/1473505.csv'), PosixPath('ipl_data/1254075_info.csv'), PosixPath('ipl_data/729303.csv'), PosixPath('ipl_data/1082625_info.csv'), PosixPath('ipl_data/392234.csv')]

In [9]:
info_files = list(data_path.glob("*_info.csv"))

print("Info files:", len(info_files))
print("\nFirst info file:", info_files[0])

with open(info_files[0], "r", encoding="utf-8") as f:
    for i in range(20):
        print(f.readline().rstrip())

Info files: 1243

First info file: ipl_data/1529264_info.csv
version,2.3.0
info,balls_per_over,6
info,team,Sunrisers Hyderabad
info,team,Rajasthan Royals
info,team_type,club
info,gender,male
info,season,2026
info,date,2026/04/13
info,event,Indian Premier League
info,match_id,1529264
info,match_type,T20
info,overs,20
info,match_number,21
info,venue,"Rajiv Gandhi International Stadium, Uppal, Hyderabad"
info,city,Hyderabad
info,toss_winner,Rajasthan Royals
info,toss_decision,field
info,player_of_match,PP Hinge
info,umpire,J Madanagopal
info,umpire,R Pandit

In [10]:
import csv

with open(info_files[0], "r", encoding="utf-8") as f:
    rows = list(csv.reader(f))

for row in rows:
    print(row)

['version', '2.3.0']
['info', 'balls_per_over', '6']
['info', 'team', 'Sunrisers Hyderabad']
['info', 'team', 'Rajasthan Royals']
['info', 'team_type', 'club']
['info', 'gender', 'male']
['info', 'season', '2026']
['info', 'date', '2026/04/13']
['info', 'event', 'Indian Premier League']
['info', 'match_id', '1529264']
['info', 'match_type', 'T20']
['info', 'overs', '20']
['info', 'match_number', '21']
['info', 'venue', 'Rajiv Gandhi International Stadium, Uppal, Hyderabad']
['info', 'city', 'Hyderabad']
['info', 'toss_winner', 'Rajasthan Royals']
['info', 'toss_decision', 'field']
['info', 'player_of_match', 'PP Hinge']
['info', 'umpire', 'J Madanagopal']
['info', 'umpire', 'R Pandit']
['info', 'reserve_umpire', 'UV Gandhe']
['info', 'tv_umpire', 'A Bengeri']
['info', 'match_referee', 'J Srinath']
['info', 'target_overs', '2', '20']
['info', 'target_runs', '2', '217']
['info', 'winner', 'Sunrisers Hyderabad']
['info', 'winner_runs', '57']
['info', 'player', 'Sunrisers Hyderabad', 'Sakib Hussain']
['info', 'player', 'Sunrisers Hyderabad', 'Abhishek Sharma']
['info', 'player', 'Sunrisers Hyderabad', 'TM Head']
['info', 'player', 'Sunrisers Hyderabad', 'Ishan Kishan']
['info', 'player', 'Sunrisers Hyderabad', 'H Klaasen']
['info', 'player', 'Sunrisers Hyderabad', 'Nithish Kumar Reddy']
['info', 'player', 'Sunrisers Hyderabad', 'S Arora']
['info', 'player', 'Sunrisers Hyderabad', 'Aniket Verma']
['info', 'player', 'Sunrisers Hyderabad', 'Harsh Dubey']
['info', 'player', 'Sunrisers Hyderabad', 'Shivang Kumar']
['info', 'player', 'Sunrisers Hyderabad', 'PP Hinge']
['info', 'player', 'Sunrisers Hyderabad', 'E Malinga']
['info', 'player', 'Rajasthan Royals', 'Sandeep Sharma']
['info', 'player', 'Rajasthan Royals', 'YBK Jaiswal']
['info', 'player', 'Rajasthan Royals', 'V Suryavanshi']
['info', 'player', 'Rajasthan Royals', 'Dhruv Jurel']
['info', 'player', 'Rajasthan Royals', 'LG Pretorius']
['info', 'player', 'Rajasthan Royals', 'R Parag']
['info', 'player', 'Rajasthan Royals', 'RA Jadeja']
['info', 'player', 'Rajasthan Royals', 'D Ferreira']
['info', 'player', 'Rajasthan Royals', 'JC Archer']
['info', 'player', 'Rajasthan Royals', 'TU Deshpande']
['info', 'player', 'Rajasthan Royals', 'Ravi Bishnoi']
['info', 'player', 'Rajasthan Royals', 'N Burger']
['info', 'registry', 'people', 'A Bengeri', 'c109497d']
['info', 'registry', 'people', 'Abhishek Sharma', 'f29185a1']
['info', 'registry', 'people', 'Aniket Verma', 'a3b0600d']
['info', 'registry', 'people', 'D Ferreira', 'f0af99a7']
['info', 'registry', 'people', 'Dhruv Jurel', 'bcf325d2']
['info', 'registry', 'people', 'E Malinga', '5750bcb4']
['info', 'registry', 'people', 'H Klaasen', '235c2bb6']
['info', 'registry', 'people', 'Harsh Dubey', '25228673']
['info', 'registry', 'people', 'Ishan Kishan', '752f7486']
['info', 'registry', 'people', 'J Madanagopal', '8275b04a']
['info', 'registry', 'people', 'J Srinath', 'bad31fac']
['info', 'registry', 'people', 'JC Archer', '5574750c']
['info', 'registry', 'people', 'LG Pretorius', '60aa2db3']
['info', 'registry', 'people', 'N Burger', '465aa633']
['info', 'registry', 'people', 'Nithish Kumar Reddy', 'aad0c365']
['info', 'registry', 'people', 'PP Hinge', 'ece7b6b3']
['info', 'registry', 'people', 'R Pandit', '8a604384']
['info', 'registry', 'people', 'R Parag', '04a418e8']
['info', 'registry', 'people', 'RA Jadeja', 'fe93fd9d']
['info', 'registry', 'people', 'Ravi Bishnoi', 'df064e1a']
['info', 'registry', 'people', 'S Arora', 'd7423da1']
['info', 'registry', 'people', 'Sakib Hussain', '280fff14']
['info', 'registry', 'people', 'Sandeep Sharma', 'ce820073']
['info', 'registry', 'people', 'Shivang Kumar', '7b44eb3e']
['info', 'registry', 'people', 'TM Head', '12b610c2']
['info', 'registry', 'people', 'TU Deshpande', '46a9bea1']
['info', 'registry', 'people', 'UV Gandhe', '43dd4011']
['info', 'registry', 'people', 'V Suryavanshi', '470f446b']
['info', 'registry', 'people', 'YBK Jaiswal', '6c19c6e5']

In [11]:
import os

for root, dirs, files in os.walk("ipl_data"):
    print(root)
    for file in files[:10]:
        print("   ", file)

ipl_data
    1529264_info.csv
    1082603_info.csv
    598019.csv
    1237181.csv
    1304065_info.csv
    1473505.csv
    1254075_info.csv
    729303.csv
    1082625_info.csv
    392234.csv

In [14]:
with open("ipl_data/1529264_info.csv", "r") as f:
    for i, line in enumerate(f):
        print(i + 1, repr(line))
        if i >= 30:
            break

1 'version,2.3.0\n'
2 'info,balls_per_over,6\n'
3 'info,team,Sunrisers Hyderabad\n'
4 'info,team,Rajasthan Royals\n'
5 'info,team_type,club\n'
6 'info,gender,male\n'
7 'info,season,2026\n'
8 'info,date,2026/04/13\n'
9 'info,event,Indian Premier League\n'
10 'info,match_id,1529264\n'
11 'info,match_type,T20\n'
12 'info,overs,20\n'
13 'info,match_number,21\n'
14 'info,venue,"Rajiv Gandhi International Stadium, Uppal, Hyderabad"\n'
15 'info,city,Hyderabad\n'
16 'info,toss_winner,Rajasthan Royals\n'
17 'info,toss_decision,field\n'
18 'info,player_of_match,PP Hinge\n'
19 'info,umpire,J Madanagopal\n'
20 'info,umpire,R Pandit\n'
21 'info,reserve_umpire,UV Gandhe\n'
22 'info,tv_umpire,A Bengeri\n'
23 'info,match_referee,J Srinath\n'
24 'info,target_overs,2,20\n'
25 'info,target_runs,2,217\n'
26 'info,winner,Sunrisers Hyderabad\n'
27 'info,winner_runs,57\n'
28 'info,player,Sunrisers Hyderabad,Sakib Hussain\n'
29 'info,player,Sunrisers Hyderabad,Abhishek Sharma\n'
30 'info,player,Sunrisers Hyderabad,TM Head\n'
31 'info,player,Sunrisers Hyderabad,Ishan Kishan\n'

In [15]:
match_df = pd.read_csv("ipl_data/598019.csv")

match_df.head()

,match_id,season,start_date,venue,innings,ball,actual_delivery,batting_team,bowling_team,striker,...,legbyes,penalty,non_boundary,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,fielder_1,fielder_2,fielder_3
0,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.1,0.1,Rajasthan Royals,Mumbai Indians,SR Watson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.2,0.2,Rajasthan Royals,Mumbai Indians,AM Rahane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.3,0.3,Rajasthan Royals,Mumbai Indians,AM Rahane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.4,0.3,Rajasthan Royals,Mumbai Indians,AM Rahane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.5,0.4,Rajasthan Royals,Mumbai Indians,SR Watson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
match_df.shape

(241, 27)

In [17]:
match_df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'actual_delivery', 'batting_team', 'bowling_team', 'striker',
       'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs',
       'byes', 'legbyes', 'penalty', 'non_boundary', 'wicket_type',
       'player_dismissed', 'other_wicket_type', 'other_player_dismissed',
       'fielder_1', 'fielder_2', 'fielder_3'],
      dtype='object')

In [18]:
ball_files = [
    file
    for file in os.listdir("ipl_data")
    if file.endswith(".csv") and not file.endswith("_info.csv")
]

print(f"Number of ball-by-ball files: {len(ball_files)}")

Number of ball-by-ball files: 1244

In [19]:
matches = []

for file in ball_files:
    df = pd.read_csv(f"ipl_data/{file}")
    matches.append(df)

ball_by_ball = pd.concat(matches, ignore_index=True)

print(f"Combined dataset shape: {ball_by_ball.shape}")

/tmp/ipykernel_1679/111266741.py:4: DtypeWarning: Columns (1,19,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"ipl_data/{file}")

Combined dataset shape: (591464, 27)

In [20]:
print("Shape:", ball_by_ball.shape)

print("\nColumns:")
print(ball_by_ball.columns.tolist())

print("\nFirst 5 rows:")
display(ball_by_ball.head())

Shape: (591464, 27)

Columns:
['match_id', 'season', 'start_date', 'venue', 'innings', 'ball', 'actual_delivery', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty', 'non_boundary', 'wicket_type', 'player_dismissed', 'other_wicket_type', 'other_player_dismissed', 'fielder_1', 'fielder_2', 'fielder_3']

First 5 rows:

,match_id,season,start_date,venue,innings,ball,actual_delivery,batting_team,bowling_team,striker,...,legbyes,penalty,non_boundary,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,fielder_1,fielder_2,fielder_3
0,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.1,0.1,Rajasthan Royals,Mumbai Indians,SR Watson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.2,0.2,Rajasthan Royals,Mumbai Indians,AM Rahane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.3,0.3,Rajasthan Royals,Mumbai Indians,AM Rahane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.4,0.3,Rajasthan Royals,Mumbai Indians,AM Rahane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,598019,2013,2013-04-17,Sawai Mansingh Stadium,1,0.5,0.4,Rajasthan Royals,Mumbai Indians,SR Watson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN