In [1]:
import requests

url = "https://cricsheet.org/downloads/ipl_csv2.zip"

response = requests.get(url)
response.raise_for_status()

with open("ipl_csv2.zip", "wb") as f:
  f.write(response.content)

print("Download complete")

Download complete

In [2]:
import zipfile

with zipfile.ZipFile("ipl_csv2.zip", "r") as zip_ref:
    zip_ref.extractall("ipl_data")

print("Extracted successfully.")

Extracted successfully.

In [3]:
from pathlib import Path

data_path = Path("ipl_data")

files = list(data_path.iterdir())

print("Number of files:", len(files))
print(files[:10])

Number of files: 2489
[PosixPath('ipl_data/1082644.csv'), PosixPath('ipl_data/1359544_info.csv'), PosixPath('ipl_data/1426261_info.csv'), PosixPath('ipl_data/1082636_info.csv'), PosixPath('ipl_data/980915_info.csv'), PosixPath('ipl_data/419164_info.csv'), PosixPath('ipl_data/829749_info.csv'), PosixPath('ipl_data/501263_info.csv'), PosixPath('ipl_data/598018.csv'), PosixPath('ipl_data/829713_info.csv')]

In [4]:
info_files = list(data_path.glob("*_info.csv"))

print("Info files:", len(info_files))
print("\nFirst info file:", info_files[0])

with open(info_files[0], "r", encoding="utf-8") as f:
    for i in range(20):
        print(f.readline().rstrip())

Info files: 1243

First info file: ipl_data/1359544_info.csv
version,2.3.0
info,balls_per_over,6
info,team,Royal Challengers Bangalore
info,team,Gujarat Titans
info,team_type,club
info,gender,male
info,season,2023
info,date,2023/05/21
info,event,Indian Premier League
info,match_id,1359544
info,match_type,T20
info,overs,20
info,match_number,70
info,venue,"M Chinnaswamy Stadium, Bengaluru"
info,city,Bengaluru
info,toss_winner,Gujarat Titans
info,toss_decision,field
info,player_of_match,Shubman Gill
info,umpire,Nitin Menon
info,umpire,VK Sharma

In [5]:
import csv

with open(info_files[0], "r", encoding="utf-8") as f:
    rows = list(csv.reader(f))

for row in rows:
    print(row)

['version', '2.3.0']
['info', 'balls_per_over', '6']
['info', 'team', 'Royal Challengers Bangalore']
['info', 'team', 'Gujarat Titans']
['info', 'team_type', 'club']
['info', 'gender', 'male']
['info', 'season', '2023']
['info', 'date', '2023/05/21']
['info', 'event', 'Indian Premier League']
['info', 'match_id', '1359544']
['info', 'match_type', 'T20']
['info', 'overs', '20']
['info', 'match_number', '70']
['info', 'venue', 'M Chinnaswamy Stadium, Bengaluru']
['info', 'city', 'Bengaluru']
['info', 'toss_winner', 'Gujarat Titans']
['info', 'toss_decision', 'field']
['info', 'player_of_match', 'Shubman Gill']
['info', 'umpire', 'Nitin Menon']
['info', 'umpire', 'VK Sharma']
['info', 'reserve_umpire', 'VM Dhokre']
['info', 'tv_umpire', 'Tapan Sharma']
['info', 'match_referee', 'J Srinath']
['info', 'target_overs', '2', '20']
['info', 'target_runs', '2', '198']
['info', 'winner', 'Gujarat Titans']
['info', 'winner_wickets', '6']
['info', 'player', 'Royal Challengers Bangalore', 'H Sharma']
['info', 'player', 'Royal Challengers Bangalore', 'V Kohli']
['info', 'player', 'Royal Challengers Bangalore', 'F du Plessis']
['info', 'player', 'Royal Challengers Bangalore', 'GJ Maxwell']
['info', 'player', 'Royal Challengers Bangalore', 'MK Lomror']
['info', 'player', 'Royal Challengers Bangalore', 'MG Bracewell']
['info', 'player', 'Royal Challengers Bangalore', 'KD Karthik']
['info', 'player', 'Royal Challengers Bangalore', 'Anuj Rawat']
['info', 'player', 'Royal Challengers Bangalore', 'HV Patel']
['info', 'player', 'Royal Challengers Bangalore', 'WD Parnell']
['info', 'player', 'Royal Challengers Bangalore', 'Vijaykumar Vyshak']
['info', 'player', 'Royal Challengers Bangalore', 'Mohammed Siraj']
['info', 'player', 'Gujarat Titans', 'Yash Dayal']
['info', 'player', 'Gujarat Titans', 'WP Saha']
['info', 'player', 'Gujarat Titans', 'Shubman Gill']
['info', 'player', 'Gujarat Titans', 'V Shankar']
['info', 'player', 'Gujarat Titans', 'MD Shanaka']
['info', 'player', 'Gujarat Titans', 'DA Miller']
['info', 'player', 'Gujarat Titans', 'R Tewatia']
['info', 'player', 'Gujarat Titans', 'HH Pandya']
['info', 'player', 'Gujarat Titans', 'Rashid Khan']
['info', 'player', 'Gujarat Titans', 'Noor Ahmad']
['info', 'player', 'Gujarat Titans', 'Mohammed Shami']
['info', 'player', 'Gujarat Titans', 'MM Sharma']
['info', 'registry', 'people', 'Anuj Rawat', 'c8f5f961']
['info', 'registry', 'people', 'DA Miller', 'd67d5f00']
['info', 'registry', 'people', 'F du Plessis', '3355b542']
['info', 'registry', 'people', 'GJ Maxwell', 'b681e71e']
['info', 'registry', 'people', 'H Sharma', '52294a79']
['info', 'registry', 'people', 'HH Pandya', 'dbe50b21']
['info', 'registry', 'people', 'HV Patel', 'f986ca1a']
['info', 'registry', 'people', 'J Srinath', 'bad31fac']
['info', 'registry', 'people', 'KD Karthik', 'c03f1114']
['info', 'registry', 'people', 'MD Shanaka', '3ff033bb']
['info', 'registry', 'people', 'MG Bracewell', 'e38bce7a']
['info', 'registry', 'people', 'MK Lomror', 'da934ee8']
['info', 'registry', 'people', 'MM Sharma', '759ac88f']
['info', 'registry', 'people', 'Mohammed Shami', '8cf9814c']
['info', 'registry', 'people', 'Mohammed Siraj', '2f49c897']
['info', 'registry', 'people', 'Nitin Menon', 'e1d41d9e']
['info', 'registry', 'people', 'Noor Ahmad', 'efc04be7']
['info', 'registry', 'people', 'R Tewatia', '39a2dfa8']
['info', 'registry', 'people', 'Rashid Khan', '5f547c8b']
['info', 'registry', 'people', 'SS Prabhudessai', '9385de2e']
['info', 'registry', 'people', 'Shubman Gill', 'b4b99816']
['info', 'registry', 'people', 'Tapan Sharma', 'b9aa2b6e']
['info', 'registry', 'people', 'V Kohli', 'ba607b88']
['info', 'registry', 'people', 'V Shankar', '0994d0ae']
['info', 'registry', 'people', 'VK Sharma', 'a7a49df4']
['info', 'registry', 'people', 'VM Dhokre', '67df71c9']
['info', 'registry', 'people', 'Vijaykumar Vyshak', '54e52590']
['info', 'registry', 'people', 'WD Parnell', '3a60e0b5']
['info', 'registry', 'people', 'WP Saha', 'fe11caa6']
['info', 'registry', 'people', 'Yash Dayal', '7210d461']

In [6]:
import pandas as pd

rows[:10]

[['version', '2.3.0'],
 ['info', 'balls_per_over', '6'],
 ['info', 'team', 'Royal Challengers Bangalore'],
 ['info', 'team', 'Gujarat Titans'],
 ['info', 'team_type', 'club'],
 ['info', 'gender', 'male'],
 ['info', 'season', '2023'],
 ['info', 'date', '2023/05/21'],
 ['info', 'event', 'Indian Premier League'],
 ['info', 'match_id', '1359544']]

In [7]:
info_data = {}

for row in rows:
    if row[0] == "info":
        key = row[1]
        value = row[2:]

        if key not in info_data:
            info_data[key] = []

        info_data[key].append(value)

info_data

{'balls_per_over': [['6']],
 'team': [['Royal Challengers Bangalore'], ['Gujarat Titans']],
 'team_type': [['club']],
 'gender': [['male']],
 'season': [['2023']],
 'date': [['2023/05/21']],
 'event': [['Indian Premier League']],
 'match_id': [['1359544']],
 'match_type': [['T20']],
 'overs': [['20']],
 'match_number': [['70']],
 'venue': [['M Chinnaswamy Stadium, Bengaluru']],
 'city': [['Bengaluru']],
 'toss_winner': [['Gujarat Titans']],
 'toss_decision': [['field']],
 'player_of_match': [['Shubman Gill']],
 'umpire': [['Nitin Menon'], ['VK Sharma']],
 'reserve_umpire': [['VM Dhokre']],
 'tv_umpire': [['Tapan Sharma']],
 'match_referee': [['J Srinath']],
 'target_overs': [['2', '20']],
 'target_runs': [['2', '198']],
 'winner': [['Gujarat Titans']],
 'winner_wickets': [['6']],
 'player': [['Royal Challengers Bangalore', 'H Sharma'],
  ['Royal Challengers Bangalore', 'V Kohli'],
  ['Royal Challengers Bangalore', 'F du Plessis'],
  ['Royal Challengers Bangalore', 'GJ Maxwell'],
  ['Royal Challengers Bangalore', 'MK Lomror'],
  ['Royal Challengers Bangalore', 'MG Bracewell'],
  ['Royal Challengers Bangalore', 'KD Karthik'],
  ['Royal Challengers Bangalore', 'Anuj Rawat'],
  ['Royal Challengers Bangalore', 'HV Patel'],
  ['Royal Challengers Bangalore', 'WD Parnell'],
  ['Royal Challengers Bangalore', 'Vijaykumar Vyshak'],
  ['Royal Challengers Bangalore', 'Mohammed Siraj'],
  ['Gujarat Titans', 'Yash Dayal'],
  ['Gujarat Titans', 'WP Saha'],
  ['Gujarat Titans', 'Shubman Gill'],
  ['Gujarat Titans', 'V Shankar'],
  ['Gujarat Titans', 'MD Shanaka'],
  ['Gujarat Titans', 'DA Miller'],
  ['Gujarat Titans', 'R Tewatia'],
  ['Gujarat Titans', 'HH Pandya'],
  ['Gujarat Titans', 'Rashid Khan'],
  ['Gujarat Titans', 'Noor Ahmad'],
  ['Gujarat Titans', 'Mohammed Shami'],
  ['Gujarat Titans', 'MM Sharma']],
 'registry': [['people', 'Anuj Rawat', 'c8f5f961'],
  ['people', 'DA Miller', 'd67d5f00'],
  ['people', 'F du Plessis', '3355b542'],
  ['people', 'GJ Maxwell', 'b681e71e'],
  ['people', 'H Sharma', '52294a79'],
  ['people', 'HH Pandya', 'dbe50b21'],
  ['people', 'HV Patel', 'f986ca1a'],
  ['people', 'J Srinath', 'bad31fac'],
  ['people', 'KD Karthik', 'c03f1114'],
  ['people', 'MD Shanaka', '3ff033bb'],
  ['people', 'MG Bracewell', 'e38bce7a'],
  ['people', 'MK Lomror', 'da934ee8'],
  ['people', 'MM Sharma', '759ac88f'],
  ['people', 'Mohammed Shami', '8cf9814c'],
  ['people', 'Mohammed Siraj', '2f49c897'],
  ['people', 'Nitin Menon', 'e1d41d9e'],
  ['people', 'Noor Ahmad', 'efc04be7'],
  ['people', 'R Tewatia', '39a2dfa8'],
  ['people', 'Rashid Khan', '5f547c8b'],
  ['people', 'SS Prabhudessai', '9385de2e'],
  ['people', 'Shubman Gill', 'b4b99816'],
  ['people', 'Tapan Sharma', 'b9aa2b6e'],
  ['people', 'V Kohli', 'ba607b88'],
  ['people', 'V Shankar', '0994d0ae'],
  ['people', 'VK Sharma', 'a7a49df4'],
  ['people', 'VM Dhokre', '67df71c9'],
  ['people', 'Vijaykumar Vyshak', '54e52590'],
  ['people', 'WD Parnell', '3a60e0b5'],
  ['people', 'WP Saha', 'fe11caa6'],
  ['people', 'Yash Dayal', '7210d461']]}

In [13]:
matches = []

for info_file in info_files:
    with open(info_file, "r", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    info_data = {}

    for row in rows:
        if len(row) >= 3 and row[0] == "info":
            key = row[1]
            value = row[2:]

            if key not in info_data:
                info_data[key] = []

            info_data[key].append(value)

    match_data = {
        "match_id": info_data["match_id"][0][0],
        "season": info_data["season"][0][0],
        "date": info_data["date"][0][0],
        "team_1": info_data["team"][0][0],
        "team_2": info_data["team"][1][0],
        "venue": info_data["venue"][0][0],
        "city": info_data["city"][0][0],
        "toss_winner": info_data["toss_winner"][0][0],
        "toss_decision": info_data["toss_decision"][0][0],
        "player_of_match": info_data.get("player_of_match", [[None]])[0][0],
        "winner": info_data.get("winner", [[None]])[0][0],
        "winner_runs": info_data.get("winner_runs", [[None]])[0][0],
        "winner_wickets": info_data.get("winner_wickets", [[None]])[0][0],
        "outcome": info_data.get("outcome", [[None]])[0][0]
    }

    matches.append(match_data)

df = pd.DataFrame(matches)

df["date"] = pd.to_datetime(df["date"])
df["winner_runs"] = pd.to_numeric(df["winner_runs"])
df["winner_wickets"] = pd.to_numeric(df["winner_wickets"])

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (1243, 14)

,match_id,season,date,team_1,team_2,venue,city,toss_winner,toss_decision,player_of_match,winner,winner_runs,winner_wickets,outcome
0,1359544,2023,2023-05-21,Royal Challengers Bangalore,Gujarat Titans,"M Chinnaswamy Stadium, Bengaluru",Bengaluru,Gujarat Titans,field,Shubman Gill,Gujarat Titans,NaN,6.0,None
1,1426261,2024,2024-04-09,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,Punjab Kings,field,Nithish Kumar Reddy,Sunrisers Hyderabad,2.0,NaN,None
2,1082636,2017,2017-05-07,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,field,SP Narine,Kolkata Knight Riders,NaN,6.0,None
3,980915,2016,2016-04-16,Sunrisers Hyderabad,Kolkata Knight Riders,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,bat,G Gambhir,Kolkata Knight Riders,NaN,8.0,None
4,419164,2009/10,2010-04-24,Royal Challengers Bangalore,Deccan Chargers,Dr DY Patil Sports Academy,Mumbai,Deccan Chargers,bat,A Kumble,Royal Challengers Bangalore,NaN,9.0,None

In [14]:
len(matches)

1243

In [15]:
df = pd.DataFrame(matches)

df.head()

,match_id,season,date,team_1,team_2,venue,city,toss_winner,toss_decision,player_of_match,winner,winner_runs,winner_wickets,outcome
0,1359544,2023,2023/05/21,Royal Challengers Bangalore,Gujarat Titans,"M Chinnaswamy Stadium, Bengaluru",Bengaluru,Gujarat Titans,field,Shubman Gill,Gujarat Titans,None,6,None
1,1426261,2024,2024/04/09,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,Punjab Kings,field,Nithish Kumar Reddy,Sunrisers Hyderabad,2,None,None
2,1082636,2017,2017/05/07,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,field,SP Narine,Kolkata Knight Riders,None,6,None
3,980915,2016,2016/04/16,Sunrisers Hyderabad,Kolkata Knight Riders,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,bat,G Gambhir,Kolkata Knight Riders,None,8,None
4,419164,2009/10,2010/04/24,Royal Challengers Bangalore,Deccan Chargers,Dr DY Patil Sports Academy,Mumbai,Deccan Chargers,bat,A Kumble,Royal Challengers Bangalore,None,9,None

In [16]:
df.shape, df.dtypes

((1243, 14),
 match_id           object
 season             object
 date               object
 team_1             object
 team_2             object
 venue              object
 city               object
 toss_winner        object
 toss_decision      object
 player_of_match    object
 winner             object
 winner_runs        object
 winner_wickets     object
 outcome            object
 dtype: object)

In [17]:
df["date"] = pd.to_datetime(df["date"])
df["winner_runs"] = pd.to_numeric(df["winner_runs"])

df.dtypes

match_id                   object
season                     object
date               datetime64[ns]
team_1                     object
team_2                     object
venue                      object
city                       object
toss_winner                object
toss_decision              object
player_of_match            object
winner                     object
winner_runs               float64
winner_wickets             object
outcome                    object
dtype: object

In [18]:
df.isna().sum()

match_id              0
season                0
date                  0
team_1                0
team_2                0
venue                 0
city                  0
toss_winner           0
toss_decision         0
player_of_match       9
winner               25
winner_runs         685
winner_wickets      583
outcome            1218
dtype: int64

In [19]:
df["match_id"].duplicated().sum()

np.int64(0)

In [20]:
df["season"].value_counts().sort_index()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
2025       74
2026       74
Name: count, dtype: int64

In [21]:
df["toss_decision"].value_counts()

toss_decision
field    825
bat      418
Name: count, dtype: int64

In [22]:
pd.unique(df[["team_1", "team_2"]].values.ravel()).size

19

In [23]:
df["date"].min(), df["date"].max()

(Timestamp('2008-04-18 00:00:00'), Timestamp('2026-05-31 00:00:00'))

In [24]:
df["winner"].value_counts()

winner
Mumbai Indians                 155
Chennai Super Kings            148
Kolkata Knight Riders          140
Rajasthan Royals               123
Royal Challengers Bangalore    114
Sunrisers Hyderabad            102
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  58
Gujarat Titans                  47
Punjab Kings                    41
Lucknow Super Giants            34
Deccan Chargers                 29
Royal Challengers Bengaluru     29
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [25]:
df["winner_runs"].describe(), df["winner_wickets"].describe()

(count    558.000000
 mean      31.035842
 std       27.162827
 min        1.000000
 25%       11.000000
 50%       23.000000
 75%       43.000000
 max      146.000000
 Name: winner_runs, dtype: float64,
 count     660
 unique     10
 top         6
 freq      140
 Name: winner_wickets, dtype: object)

In [26]:
df["outcome"].value_counts(dropna=False)

outcome
None         1218
tie            16
no result       9
Name: count, dtype: int64

In [27]:
print("Wins by runs:", df["winner_runs"].notna().sum())
print("Wins by wickets:", df["winner_wickets"].notna().sum())
print("Matches without a recorded winner:", df["winner"].isna().sum())

Wins by runs: 558
Wins by wickets: 660
Matches without a recorded winner: 25

#Work for Next Day

In [28]:
team_appearances = (
    df["team_1"].value_counts()
    .add(df["team_2"].value_counts(), fill_value=0)
    .sort_values(ascending=False)
)

team_appearances

Mumbai Indians                 291
Kolkata Knight Riders          278
Chennai Super Kings            266
Rajasthan Royals               251
Royal Challengers Bangalore    240
Sunrisers Hyderabad            211
Kings XI Punjab                190
Delhi Daredevils               161
Delhi Capitals                 120
Punjab Kings                    88
Gujarat Titans                  77
Deccan Chargers                 75
Lucknow Super Giants            72
Royal Challengers Bengaluru     46
Pune Warriors                   46
Gujarat Lions                   30
Rising Pune Supergiant          16
Kochi Tuskers Kerala            14
Rising Pune Supergiants         14
Name: count, dtype: int64

In [29]:
team_wins = df["winner"].value_counts()

team_wins

winner
Mumbai Indians                 155
Chennai Super Kings            148
Kolkata Knight Riders          140
Rajasthan Royals               123
Royal Challengers Bangalore    114
Sunrisers Hyderabad            102
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  58
Gujarat Titans                  47
Punjab Kings                    41
Lucknow Super Giants            34
Deccan Chargers                 29
Royal Challengers Bengaluru     29
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [31]:
team_summary = pd.DataFrame({
    "matches_played": team_appearances,
    "matches_won": team_wins
}).fillna(0)

team_summary["matches_won"] = team_summary["matches_won"].astype(int)

team_summary

                             matches_played  matches_won
Chennai Super Kings                     266          148
Deccan Chargers                          75           29
Delhi Capitals                          120           58
Delhi Daredevils                        161           67
Gujarat Lions                            30           13
Gujarat Titans                           77           47
Kings XI Punjab                         190           85
Kochi Tuskers Kerala                     14            6
Kolkata Knight Riders                   278          140
Lucknow Super Giants                     72           34
Mumbai Indians                          291          155
Pune Warriors                            46           12
Punjab Kings                             88           41
Rajasthan Royals                        251          123
Rising Pune Supergiant                   16           10
Rising Pune Supergiants                  14            5
Royal Challengers Bangalore             240          114
Royal Challengers Bengaluru              46           29
Sunrisers Hyderabad                     211          102

In [32]:
team_summary["win_percentage"] = (
    team_summary["matches_won"] / team_summary["matches_played"] * 100
).round(2)

team_summary.sort_values("win_percentage", ascending=False)

                             matches_played  matches_won  win_percentage
Royal Challengers Bengaluru              46           29           63.04
Rising Pune Supergiant                   16           10           62.50
Gujarat Titans                           77           47           61.04
Chennai Super Kings                     266          148           55.64
Mumbai Indians                          291          155           53.26
Kolkata Knight Riders                   278          140           50.36
Rajasthan Royals                        251          123           49.00
Sunrisers Hyderabad                     211          102           48.34
Delhi Capitals                          120           58           48.33
Royal Challengers Bangalore             240          114           47.50
Lucknow Super Giants                     72           34           47.22
Punjab Kings                             88           41           46.59
Kings XI Punjab                         190           85           44.74
Gujarat Lions                            30           13           43.33
Kochi Tuskers Kerala                     14            6           42.86
Delhi Daredevils                        161           67           41.61
Deccan Chargers                          75           29           38.67
Rising Pune Supergiants                  14            5           35.71
Pune Warriors                            46           12           26.09